-- CreateTable
CREATE TABLE `TBL_PNC` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `PNREGID` VARCHAR(20) NOT NULL,
    `PNPROVIDEDDATE` DATETIME(3) NULL,
    `PNAGE` INTEGER NOT NULL DEFAULT 999,
    `PNTYPE` INTEGER NOT NULL DEFAULT 999,
    `PNDONOR` VARCHAR(10) NULL,
    `PNORG` VARCHAR(10) NULL,
    `PNPROJECT` VARCHAR(10) NULL,
    `PNTSP` VARCHAR(100) NULL,
    `PNPLACE` INTEGER NOT NULL DEFAULT 999,
    `PNVILLAGE` VARCHAR(20) NULL,
    `PNPROVIDERNAME` VARCHAR(30) NULL,
    `PNANSELFREP` INTEGER NOT NULL DEFAULT 999,
    `PNPROVIDERPOSITION` INTEGER NOT NULL DEFAULT 999,
    `PNUSRLOGIN` VARCHAR(100) NULL,
    `PNWT` DOUBLE NOT NULL DEFAULT 999.90,
    `PNHT` DOUBLE NOT NULL DEFAULT 999.90,
    `PNBP` VARCHAR(10) NULL DEFAULT '000/00',
    `PNPR` INTEGER NOT NULL DEFAULT 999,
    `PNRR` INTEGER NOT NULL DEFAULT 999,
    `PNTEMP` DOUBLE NOT NULL DEFAULT 999.90,
    `PNP` INTEGER NOT NULL DEFAULT 999,
    `PNA` INTEGER NOT NULL DEFAULT 999,
    `PNANAEMIA` INTEGER NOT NULL DEFAULT 999,
    `PNNIPPLE` INTEGER NOT NULL DEFAULT 999,
    `PNUTRCONTRACTION` INTEGER NOT NULL DEFAULT 999,
    `PNVAGBLEEDING` INTEGER NOT NULL DEFAULT 999,
    `PNWOUNDCOND` INTEGER NOT NULL DEFAULT 999,
    `PNLAB` INTEGER NOT NULL DEFAULT 0,
    `PNSEPSIS` INTEGER NOT NULL DEFAULT 999,
    `PNPPH` INTEGER NOT NULL DEFAULT 999,
    `PNRPOC` INTEGER NOT NULL DEFAULT 999,
    `PNECLAMPSIA` INTEGER NOT NULL DEFAULT 999,
    `PNBTABSCESS` INTEGER NOT NULL DEFAULT 999,
    `PNINF` INTEGER NOT NULL DEFAULT 999,
    `PNMALARIA` INTEGER NOT NULL DEFAULT 999,
    `PNTRANSFUSION` INTEGER NOT NULL DEFAULT 999,
    `PNMVA` INTEGER NOT NULL DEFAULT 999,
    `PNREMOVALPLACENTA` INTEGER NOT NULL DEFAULT 999,
    `PNOXYTOCIN` INTEGER NOT NULL DEFAULT 999,
    `PNANTIBIOTICINJ` INTEGER NOT NULL DEFAULT 999,
    `PNMISO` INTEGER NOT NULL DEFAULT 999,
    `PNANTICONVULSANT` INTEGER NOT NULL DEFAULT 999,
    `PNMALARIATX` INTEGER NOT NULL DEFAULT 999,
    `PNB1` INTEGER NOT NULL DEFAULT 999,
    `PNVITA` INTEGER NOT NULL DEFAULT 999,
    `PNFESO4` INTEGER NOT NULL DEFAULT 999,
    `PNFP` INTEGER NOT NULL DEFAULT 999,
    `PNOUTCOME` INTEGER NOT NULL DEFAULT 999,
    `PNREFTO` INTEGER NOT NULL DEFAULT 999,
    `PNREFTOOTHER` VARCHAR(255) NULL,
    `PNREFREASON` VARCHAR(255) NULL,
    `PNDEATHREASON` VARCHAR(255) NULL,
    `PNINSERT` DATETIME(3) NULL,
    `PNHE` INTEGER NOT NULL DEFAULT 999,
    `PNDDELI` DATETIME(3) NULL,
    `PN3DAYS` INTEGER NOT NULL DEFAULT 999,
    `PNB1UNIT` INTEGER NOT NULL DEFAULT 999,
    `PNANTIBIOTICPO` INTEGER NOT NULL DEFAULT 999,
    `PNTEO` INTEGER NOT NULL DEFAULT 999,
    `PNTX` INTEGER NOT NULL DEFAULT 999,
    `PNDXOTHER` VARCHAR(1000) NULL,
    `PNTXOTHER` VARCHAR(1000) NULL,
    `PNAGEUNIT` INTEGER NOT NULL DEFAULT 999,
    `PNDX` INTEGER NOT NULL DEFAULT 999,
    `PNTEMPUNIT` INTEGER NOT NULL DEFAULT 999,
    `PNVITAUNIT` INTEGER NOT NULL DEFAULT 999,
    `PNCLNID` VARCHAR(10) NULL,
    `PNUPDATE` DATETIME(3) NULL,
    `PNSTATUS` INTEGER NOT NULL DEFAULT 0,
    `PNSYNC` INTEGER NOT NULL DEFAULT 0,
    `PNREMARK` VARCHAR(1000) NULL,
    `PNNBC` INTEGER NOT NULL DEFAULT 0,
    `PNMIGRANT` INTEGER NOT NULL DEFAULT 999,
    `PNIDP` INTEGER NOT NULL DEFAULT 999,
    `PNDSEE` INTEGER NOT NULL DEFAULT 999,
    `PNDHEAR` INTEGER NOT NULL DEFAULT 999,
    `PNDWALK` INTEGER NOT NULL DEFAULT 999,
    `PNDREMBR` INTEGER NOT NULL DEFAULT 999,
    `PNDWASH` INTEGER NOT NULL DEFAULT 999,
    `PNDCOMMU` INTEGER NOT NULL DEFAULT 999,
    `PNDISABILITY` INTEGER NOT NULL DEFAULT 999,
    `PNBSEX1` INTEGER NOT NULL DEFAULT 999,
    `PNBSEX2` INTEGER NOT NULL DEFAULT 999,
    `PNBSEX3` INTEGER NOT NULL DEFAULT 999,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TBL_DELIVERY` ADD CONSTRAINT `TBL_DELIVERY_DELIREGID_fkey` FOREIGN KEY (`DELIREGID`) REFERENCES `TBL_REG`(`REGID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TBL_DELIVERY` ADD CONSTRAINT `TBL_DELIVERY_DELICLNID_fkey` FOREIGN KEY (`DELICLNID`) REFERENCES `TBL_CLINIC`(`CLN_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TBL_DELIVERY` ADD CONSTRAINT `TBL_DELIVERY_DELIORG_fkey` FOREIGN KEY (`DELIORG`) REFERENCES `TBL_ORG`(`ORG_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TBL_PNC` ADD CONSTRAINT `TBL_PNC_PNREGID_fkey` FOREIGN KEY (`PNREGID`) REFERENCES `TBL_REG`(`REGID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TBL_PNC` ADD CONSTRAINT `TBL_PNC_PNCLNID_fkey` FOREIGN KEY (`PNCLNID`) REFERENCES `TBL_CLINIC`(`CLN_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TBL_PNC` ADD CONSTRAINT `TBL_PNC_PNORG_fkey` FOREIGN KEY (`PNORG`) REFERENCES `TBL_ORG`(`ORG_ID`) ON DELETE SET NULL ON UPDATE CASCADE;
