-- AlterTable
ALTER TABLE `Employee` ADD COLUMN `bloodType` VARCHAR(20) NULL,
    ADD COLUMN `currentAddress` VARCHAR(20) NULL,
    ADD COLUMN `currentContractPeriod` INTEGER NULL,
    ADD COLUMN `dateOfBirth` DATE NULL,
    ADD COLUMN `emergencyContactInfo` VARCHAR(20) NULL,
    ADD COLUMN `employeeCode` VARCHAR(20) NULL,
    ADD COLUMN `enrollInKNUDate` DATE NULL,
    ADD COLUMN `ethnicity` VARCHAR(20) NULL,
    ADD COLUMN `fatherName` VARCHAR(20) NULL,
    ADD COLUMN `gender` VARCHAR(20) NULL,
    ADD COLUMN `gradeLevel` INTEGER NULL,
    ADD COLUMN `homeAddress` VARCHAR(20) NULL,
    ADD COLUMN `idNumber` VARCHAR(20) NULL,
    ADD COLUMN `motherName` VARCHAR(20) NULL,
    ADD COLUMN `nameInBurmese` VARCHAR(20) NULL,
    ADD COLUMN `nameInKaren` VARCHAR(20) NULL,
    ADD COLUMN `nationality` VARCHAR(20) NULL,
    ADD COLUMN `placeCodeNo` VARCHAR(20) NULL,
    ADD COLUMN `propationPeriod` INTEGER NULL,
    ADD COLUMN `religion` VARCHAR(20) NULL,
    ADD COLUMN `trainingLevel` VARCHAR(20) NULL,
    ADD COLUMN `typeOfId` VARCHAR(20) NULL,
    ADD COLUMN `workloads` VARCHAR(20) NULL;
