-- CreateTable
CREATE TABLE `TBL_DIAGNOSIS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `DXCODE` INTEGER NOT NULL DEFAULT 0,
    `DIAGNOSIS` VARCHAR(255) NULL,
    `DXCPI` INTEGER NOT NULL DEFAULT 999,
    `DXCHDN` INTEGER NOT NULL DEFAULT 999,
    `DXSSDF` INTEGER NOT NULL DEFAULT 999,
    `DXTNTH` VARCHAR(1000) NULL,
    `DXMNHC` INTEGER NOT NULL DEFAULT 999,
    `DXICD` INTEGER NOT NULL DEFAULT 999,
    `DXICD11` VARCHAR(20) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TBL_DISEASE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DIS_CODE` VARCHAR(20) NULL,
    `DIS_CODELBL` VARCHAR(30) NULL,
    `DIS_NAME` VARCHAR(255) NULL,
    `DIS_DESCRIPTION` VARCHAR(255) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TBL_GM` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `GMREGID` VARCHAR(20) NOT NULL,
    `GMAGE` INTEGER NOT NULL DEFAULT 999,
    `GMPROVIDEDDATE` DATETIME(3) NULL,
    `GMTYPE` INTEGER NOT NULL DEFAULT 999,
    `GMDONOR` VARCHAR(10) NULL,
    `GMORG` VARCHAR(10) NULL,
    `GMPROJECT` VARCHAR(10) NULL,
    `GMTSP` VARCHAR(20) NULL,
    `GMPLACE` INTEGER NOT NULL DEFAULT 999,
    `GMVILLAGE` VARCHAR(20) NULL,
    `GMPROVIDERNAME` VARCHAR(30) NULL,
    `GMPROVIDERPOSITION` INTEGER NOT NULL DEFAULT 999,
    `GMUSRLOGIN` VARCHAR(30) NULL,
    `GMWT` DOUBLE NOT NULL DEFAULT 999.90,
    `GMHT` DOUBLE NOT NULL DEFAULT 999.90,
    `GMBP` VARCHAR(15) NOT NULL DEFAULT '000/000',
    `GMPR` INTEGER NOT NULL DEFAULT 999,
    `GMRR` INTEGER NOT NULL DEFAULT 999,
    `GMTEMP` DOUBLE NOT NULL DEFAULT 999.90,
    `GMP` INTEGER NOT NULL DEFAULT 999,
    `GMA` INTEGER NOT NULL DEFAULT 999,
    `GMHE` INTEGER NOT NULL DEFAULT 999,
    `GMGMTYPE` INTEGER NOT NULL DEFAULT 999,
    `GMPREG` INTEGER NOT NULL DEFAULT 999,
    `GMLAB` INTEGER NOT NULL DEFAULT 0,
    `GMOTHERDX` VARCHAR(1000) NULL,
    `GMDX1` INTEGER NOT NULL DEFAULT 999,
    `GMDX2` INTEGER NOT NULL DEFAULT 999,
    `GMDX3` INTEGER NOT NULL DEFAULT 999,
    `GMCOMPLAINT` VARCHAR(1000) NULL,
    `GMPROCEDURE` VARCHAR(1000) NULL,
    `GMTX` VARCHAR(1000) NULL,
    `GMOUTCOME` INTEGER NOT NULL DEFAULT 999,
    `GMREFTO` INTEGER NOT NULL DEFAULT 999,
    `GMREFTOOTHER` VARCHAR(255) NULL,
    `GMREFREASON` VARCHAR(255) NULL,
    `GMDEATHREASON` VARCHAR(255) NULL,
    `GMAGEUNIT` INTEGER NOT NULL DEFAULT 999,
    `GMSS` VARCHAR(1000) NULL,
    `GMPE` VARCHAR(1000) NULL,
    `GMTEMPUNIT` INTEGER NOT NULL DEFAULT 999,
    `GMHEPB` INTEGER NOT NULL DEFAULT 999,
    `GMCLNID` VARCHAR(10) NULL,
    `GMINSERT` DATETIME(3) NULL,
    `GMUPDATE` DATETIME(3) NULL,
    `GMSTATUS` INTEGER NOT NULL DEFAULT 0,
    `GMSYNC` INTEGER NOT NULL DEFAULT 0,
    `GMREMARK` VARCHAR(255) NULL,
    `GMMUAC` DOUBLE NULL,
    `GMDXSTATUS` INTEGER NOT NULL DEFAULT 0,
    `GMMIGRANT` INTEGER NOT NULL DEFAULT 999,
    `GMIDP` INTEGER NOT NULL DEFAULT 999,
    `GMDSEE` INTEGER NOT NULL DEFAULT 999,
    `GMDHEAR` INTEGER NOT NULL DEFAULT 999,
    `GMDWALK` INTEGER NOT NULL DEFAULT 999,
    `GMDREMBR` INTEGER NOT NULL DEFAULT 999,
    `GMDWASH` INTEGER NOT NULL DEFAULT 999,
    `GMDCOMMU` INTEGER NOT NULL DEFAULT 999,
    `GMLACMOTHER` INTEGER NOT NULL DEFAULT 999,
    `GMDISABILITY` INTEGER NOT NULL DEFAULT 999,
    `GMDIARRHOEA` INTEGER NOT NULL DEFAULT 999,
    `GMPNEUMONIA` INTEGER NOT NULL DEFAULT 999,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TBL_GM` ADD CONSTRAINT `TBL_GM_GMREGID_fkey` FOREIGN KEY (`GMREGID`) REFERENCES `TBL_REG`(`REGID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TBL_GM` ADD CONSTRAINT `TBL_GM_GMCLNID_fkey` FOREIGN KEY (`GMCLNID`) REFERENCES `TBL_CLINIC`(`CLN_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TBL_GM` ADD CONSTRAINT `TBL_GM_GMORG_fkey` FOREIGN KEY (`GMORG`) REFERENCES `TBL_ORG`(`ORG_ID`) ON DELETE SET NULL ON UPDATE CASCADE;
